---
AWSTemplateFormatVersion: "2010-09-09"
Description: >
  ECR

Parameters:
  ProjectName:
    Type: String
    Default: "default"
    Description: "Project(Service) name"
  Env:
    Type: String
    Default: "dev"
    Description: "Environment"
  Role:
    Type: String
    Default: ""
    Description: ""

Resources:
  # ECR
  Repository:
    Type: "AWS::ECR::Repository"
    Properties:
      RepositoryName: !Sub "${ProjectName}-${Env}/${Role}"
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Env}-${Role}-ecr"
        - Key: Env
          Value: !Ref Env
        - Key: Role
          Value: !Ref Role
