---
AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Route53

Parameters:
  ProjectName:
    Type: String
    Default: "default"
    Description: "Project(Service) name"
  DomainName:
    Type: String
    Description: ""
  Logging:
    Type: String
    Default: "false"
    Description: "Query log to Cloudwatch Logs"
    AllowedValues:
      - "true"
      - "false"
  RetentionInDays:
    Type: Number
    Default: 7
    Description: "Log Retention Period (Enabled when the Logging parameter is true)"

Conditions:
  IsLogging: !Equals [ !Ref Logging, "true" ]

Outputs:
  HostedZoneId:
    Value: !Ref HostedZone
    Export:
      Name: !Sub "${ProjectName}-hostedzone-id"

Resources:
  # Route53 HostedZone
  HostedZone:
    Type: "AWS::Route53::HostedZone"
    Properties:
      HostedZoneConfig:
        Comment: !Sub "${ProjectName} hostedzone"
      Name: !Ref DomainName
      QueryLoggingConfig: !If
        - IsLogging
        - CloudWatchLogsLogGroupArn: !GetAtt LogGroup.Arn
        - !Ref AWS::NoValue

  # CloudWatch LogGroup
  LogGroup:
    Type: "AWS::Logs::LogGroup"
    Condition: IsLogging
    Properties:
      LogGroupName: !Sub "/aws/route53/${DomainName}"
      RetentionInDays: !Ref RetentionInDays
