---
AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Route53

Parameters:
  ProjectName:
    Type: String
    Default: default
    Description: "Project(Service) name"
    MaxLength: 10
    MinLength: 2
  DomainName:
    Type: String
    Description: ""
  Logging:
    Type: String
    Default: false
    Description: "(Option) Query log to CloudWatch Logs"
    AllowedValues:
      - true
      - false

Conditions:
  Logging: !Equals [ !Ref Logging, "true" ]

Outputs:
  HostedZoneId:
    Value: !Ref HostedZone
    Export:
      Name: !Sub "${ProjectName}-hostedzone-id"

Resources:
  # Route53 HostedZone
  HostedZone:
    Type: "AWS::Route53::HostedZone"
    Properties:
      HostedZoneConfig:
        Comment: !Sub "${ProjectName} hostedzone"
      Name: !Ref DomainName
      QueryLoggingConfig: !If
        - Logging
        - CloudWatchLogsLogGroupArn: !GetAtt LogGroup.Arn
        - !Ref AWS::NoValue

  # CloudWatch LogGroup
  LogGroup:
    Type: "AWS::Logs::LogGroup"
    Properties:
      LogGroupName: !Sub "/aws/route53/${DomainName}"
      RetentionInDays: 30
