---
AWSTemplateFormatVersion: "2010-09-09"
Description: >
  S3

Parameters:
  ProjectName:
    Type: String
    Default: "default"
    Description: "Project(Service) name"
  Env:
    Type: String
    Default: "dev"
    Description: "Environment"
  Role:
    Type: String
    Default: ""
    Description: ""
  Logging:
    Type: String
    Default: "false"
    Description: "ALB Logging option"
    AllowedValues:
      - "true"
      - "false"
  ExpirationInDays:
    Type: Number
    Default: 7
    Description: "Log Retention Period (Enabled when the Logging parameter is true)"

Conditions:
  IsLogging: !Equals [ !Ref Logging, "true" ]

Resources:
  # S3 Buckets
  Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Sub "${ProjectName}-${Env}-${Role}"
      LifecycleConfiguration:
        Rules: !If
          - IsLogging
          -
            - ExpirationInDays: !Ref ExpirationInDays
              Status: "Enabled"
          - !Ref AWS::NoValue
      Tags:
        - Key: ProjectName
          Value: !Ref ProjectName
        - Key: Env
          Value: !Ref Env
        - Key: Role
          Value: !Ref Role

  BucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Condition: IsLogging
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "LogBucketPolicy"
            Effect: "Allow"
            Principal:
              AWS:
                - "arn:aws:iam::582318560864:root"
            Action: "s3:PutObject"
            Resource: !Sub "arn:aws:s3:::${Bucket}/AWSLogs/${AWS::AccountId}/*"
