---
AWSTemplateFormatVersion: "2010-09-09"
Description: >
  S3

Parameters:
  ProjectName:
    Type: String
    Default: default
    Description: "Project(Service) name"
    MaxLength: 10
    MinLength: 2
  Env:
    Type: String
    Default: dev
    Description: "Environment"
    AllowedValues:
      - dev
      - stg
      - prd

Resources:
  # S3 Bucket
  LogBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Sub "${ProjectName}-${Env}-logs"
      LifecycleConfiguration:
        Rules:
          - ExpirationInDays: 30
            Status: "Enabled"
      Tags:
        - Key: Env
          Value: !Ref Env

  DeployBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Sub "${ProjectName}-${Env}-deploy"
      Tags:
        - Key: Env
          Value: !Ref Env
