---
AWSTemplateFormatVersion: "2010-09-09"
Description: >
  S3

Parameters:
  ProjectName:
    Type: String
    Default: default
    Description: "Project(Service) name"
    MaxLength: 10
    MinLength: 2
  Env:
    Type: String
    Default: dev
    Description: "Environment"
    AllowedValues:
      - dev
      - stg
      - prd

Resources:
  # S3 Buckets
  # for any logs
  LogBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Sub "${ProjectName}-${Env}-logs"
      LifecycleConfiguration:
        Rules:
          - ExpirationInDays: 30
            Status: "Enabled"
      Tags:
        - Key: ProjectName
          Value: !Ref ProjectName
        - Key: Env
          Value: !Ref Env

  BucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref LogBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "ALBLogBucketPolicy"
            Effect: "Allow"
            Principal:
              AWS:
                - "582318560864"
            Action: "s3:PutObject"
            Resource: !Sub "arn:aws:s3:::${LogBucket}/AWSLogs/${AWS::AccountId}/*"

  # for application codes
  DeployBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Sub "${ProjectName}-${Env}-deploy"
      Tags:
        - Key: ProjectName
          Value: !Ref ProjectName
        - Key: Env
          Value: !Ref Env

  # for SAM packages
  SamBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Sub "${ProjectName}-${Env}-sam"
      Tags:
        - Key: ProjectName
          Value: !Ref ProjectName
        - Key: Env
          Value: !Ref Env
