---
AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Serverless Aurora

Parameters:
  ProjectName:
    Type: String
    Default: "default"
    Description: "Project(Service) name"
    MaxLength: 10
    MinLength: 2
  Env:
    Type: String
    Default: "dev"
    Description: "Environment"
    AllowedValues:
      - "dev"
      - "stg"
      - "prd"
  Role:
    Type: String
    Default: "app"
    Description: ""
  MasterUsername:
    Type: String
    Default: admin
    Description: "Database default user name"
  MasterUserPassword:
    Type: String
    Description: "Database default user password"
    NoEcho: true
  DomainName:
    Type: String
    Default: ""
    Description: ""
  AdmFlag:
    Type: String
    Default: "false"
    Description: "Launch adm subnet flag (default: false)"
    AllowedValues:
      - "true"
      - "false"

Conditions:
  IsAdmSubnet: !Equals [ !Ref AdmFlag, "true"]

Resources:
  # Security Group
  SecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: !Sub "for ${Role} rds"
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          FromPort: 3306
          ToPort: 3306
          CidrIp: { "Fn::ImportValue": !Sub "${ProjectName}-${Env}-vpc-cidr" }
          Description: !Join
            - " "
            - - "from"
              - { "Fn::ImportValue": !Sub "${ProjectName}-${Env}-vpc" }
              - "any instances"
      SecurityGroupEgress:
        - IpProtocol : "-1"
          CidrIp: "0.0.0.0/0"
      VpcId: { "Fn::ImportValue": !Sub "${ProjectName}-${Env}-vpc" }
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Env}-${Role}-rds-sg"
        - Key: Env
          Value: !Ref Env
        - Key: Role
          Value: !Ref Role

  # Cluster Parameter Group
  ClusterParameterGroup:
    Type: "AWS::RDS::DBClusterParameterGroup"
    Properties:
      Description: !Sub "for ${Role} rds"
      Family: "aurora5.6"
      Parameters:
        character_set_database: "utf8"
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Env}-${Role}-param-cluster"
        - Key: Env
          Value: !Ref Env
        - Key: Role
          Value: !Ref Role

  # Subnet Group
  SubnetGroup:
    Type: "AWS::RDS::DBSubnetGroup"
    Properties:
      DBSubnetGroupName: !Sub "${ProjectName}-${Env}-${Role}-subnet"
      DBSubnetGroupDescription: !Sub "for ${Role} rds"
      SubnetIds: !If
        - IsAdmSubnet
        -
          - { "Fn::ImportValue": !Sub "${ProjectName}-${Env}-adm-pri-uno-subnet" }
          - { "Fn::ImportValue": !Sub "${ProjectName}-${Env}-adm-pri-due-subnet" }
        -
          - { "Fn::ImportValue": !Sub "${ProjectName}-${Env}-pri-uno-subnet" }
          - { "Fn::ImportValue": !Sub "${ProjectName}-${Env}-pri-due-subnet" }
          - { "Fn::ImportValue": !Sub "${ProjectName}-${Env}-pri-tri-subnet" }

  # Severless Aurora DB Cluster
  DbCuster:
    Type: "AWS::RDS::DBCluster"
    Properties:
      AvailabilityZones: !If
        - IsAdmSubnet
        -
          - !Select [ "0", !GetAZs ""]
          - !Select [ "1", !GetAZs ""]
        -
          - !Select [ "0", !GetAZs ""]
          - !Select [ "1", !GetAZs ""]
          - !Select [ "2", !GetAZs ""]
      BackupRetentionPeriod: 3
      DBClusterParameterGroupName: !Ref ClusterParameterGroup
      DBSubnetGroupName: !Ref SubnetGroup
      Engine: "aurora"
      EngineMode: "serverless"
      EngineVersion: "5.6.10a"
      MasterUsername: !Ref MasterUsername
      MasterUserPassword: !Ref MasterUserPassword
      PreferredBackupWindow: "14:30-15:00"
      PreferredMaintenanceWindow: "sat:15:00-sat:15:30"
      ScalingConfiguration:
        AutoPause: true
        MaxCapacity: 4
        MinCapacity: 1
        SecondsUntilAutoPause: 300
      VpcSecurityGroupIds:
        - !Ref SecurityGroup
      Tags:
        - Key: Env
          Value: !Ref Env
        - Key: Role
          Value: !Ref Role

  # Set Route53 record
  SetRecord:
    Type: "AWS::Route53::RecordSet"
    Properties:
      Comment: !Sub "for ${Role}"
      HostedZoneName: !Sub "${DomainName}."
      Name: !Sub "${Role}-db.${DomainName}"
      ResourceRecords:
        - !GetAtt DbCuster.Endpoint.Address
      TTL: "60"
      Type: "CNAME"
