AWSTemplateFormatVersion: '2010-09-09'
Description: >
  AWS Transfer for SFTP User

Parameters:
  ProjectName:
    Type: String
    Description: ""
  Env:
    Type: String
    Default: "dev"
    Description: ""
    AllowedValues:
      - dev
      - stg
      - prd
  Role:
    Type: String
    Default: "sftp"
    Description: ""
  UserName:
    Type: String
    Description: ""
  SshPubKey:
    Type: String
    Description: ""

Resources:
  # SFTP
  # https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-resource-transfer-user.html
  SftpUser:
    Type: "AWS::Transfer::User"
    Properties:
      HomeDirectory: !Join
        - "/"
        - - ""
          - Fn::ImportValue: !Sub "${ProjectName}-${Env}-${Role}-bucket"
      Role: { "Fn::ImportValue": !Sub "${ProjectName}-${Env}-${Role}-iam-role" }
      ServerId: { "Fn::ImportValue": !Sub "${ProjectName}-${Env}-${Role}-srv" }
      UserName: !Ref UserName
      SshPublicKeys:
        - !Ref SshPubKey
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Env}-${Role}-${UserName}"
        - Key: Env
          Value: !Ref Env
        - Key: Role
          Value: !Ref Role
